//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProy
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Domicilio
    {
        public int id { get; set; }
        [StringLength(50)]
        [Required]
        public string Calle { get; set; }
        [DisplayName("Número")]
        [Required]
        [Range(0, int.MaxValue)]
        public Nullable<int> Numero { get; set; }
        public Nullable<int> Persona_id { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
